### PR TITLE
adding classical solvers for LABS

### PR DESCRIPTION
**Pull request by rsln-s**
Requested by @jmlarson1

### CODE REVIEW

**Comment by jmlarson1** [comment]
I observe the following: 

Am I not setting things up correctly?

````
[jlarson@x1carbon classical_solvers_for_LABS] python generate_lp_files.py True 20 25
Generating LABS for n=20 in /home/jlarson/QOKit/examples/classical_solvers_for_LABS/lp/LABS_n20_cplex.lp
Generating LABS for n=21 in /home/jlarson/QOKit/examples/classical_solvers_for_LABS/lp/LABS_n21_cplex.lp
Generating LABS for n=22 in /home/jlarson/QOKit/examples/classical_solvers_for_LABS/lp/LABS_n22_cplex.lp
Generating LABS for n=23 in /home/jlarson/QOKit/examples/classical_solvers_for_LABS/lp/LABS_n23_cplex.lp
Generating LABS for n=24 in /home/jlarson/QOKit/examples/classical_solvers_for_LABS/lp/LABS_n24_cplex.lp

[jlarson@x1carbon classical_solvers_for_LABS] python3 run_gurobi.py TTS 10 20 10
Set parameter Username
Academic license - for non-commercial use only - expires 2024-10-24
Traceback (most recent call last):
  File "/home/jlarson/QOKit/examples/classical_solvers_for_LABS/run_gurobi.py", line 98, in <module>
    run_LABS(range(n_min, n_max), TTS=TTS, env=env, nb_runs=nb_runs)
  File "/home/jlarson/QOKit/examples/classical_solvers_for_LABS/run_gurobi.py", line 72, in run_LABS
    msol, raw_time_diff, time_diff = run_one_instance(path_lp, env, TTS=TTS, n=n, log_to_write=log_to_write, seed=seed_gurobi)
  File "/home/jlarson/QOKit/examples/classical_solvers_for_LABS/run_gurobi.py", line 29, in run_one_instance
    m.setParam(GRB.Param.Cuts, Cuts)
UnboundLocalError: local variable 'm' referenced before assignment
````

**Comment by rsln-s** [comment]
Hi @jmlarson1,

`python generate_lp_files.py True 20 25` generates LP files for N between 20 and 25, but `python run_gurobi.py TTS 10 20 10` is trying to load files with N between 10 and 20. I have updated the doctoring to remove this confusion. 

Can you try the following?

```bash
python generate_lp_files.py True 10 20
python run_gurobi.py TTS 10 20 10
```

**Comment by rsln-s** [comment]
@rajgane07, would you mind checking why the deployment build is failing and how that can be fixed?

**Comment by jmlarson1** [comment]
That works for me: 

````
[jlarson@x1carbon classical_solvers_for_LABS] tail logs_gurobi/gurobi_time_TTS_LABS_Threads_8_Cuts_0_Heuristics_0.csv
19,58.831720579999995,7.424087285995483,19576,0
19,51.76362204600002,6.8362038135528564,14306,1
19,47.279728691,6.627930402755737,11072,2
19,79.92150198500002,10.984905481338501,17953,3
19,47.29674707199996,7.276442766189575,9029,4
19,59.619839663999926,8.433784246444702,14497,5
19,39.214781344000016,5.138017177581787,10016,6
19,38.337952210000026,4.904386520385742,11664,7
19,39.834180751000076,5.080341100692749,12864,8
19,31.600170090999995,4.0231029987335205,9512,9

````

**Comment by rsln-s** [comment]
Great! I will merge.

**Review by alex124585 — APPROVED** [review]

**Pull request merged**
