### PR TITLE
Adding missing commits from private mirror

### PR DESCRIPTION
**Pull request by rsln-s**

### CODE REVIEW

**Comment by rsln-s** [comment]
Should be good to merge after @ZichangHe reviews as this is simply a sync of commits that were missed during the open-sourcing process.

**Comment by ZichangHe** [comment]
All test passed in my local repo.

I found two errors (easy to fix) by running example notebooks:
1. `parameter_utils.get_LABS_wrt_best_overlap` function is missing 
2. `nlopt` is not installed automatically

Anything else specific to look at?

**Comment by rsln-s** [comment]
Thanks for checking! Would you mind fixing? For (1), just change the function call to the correct one. For (2), add a comment in notebook to install nlopt as an optional dependency (`pip install nlopt`)

**Comment by ZichangHe** [comment]
Done. Should be good to merge.

**Review by ZichangHe — COMMENTED** [review]
Looks good. We now have only one `get_qaoa_objective` now (`get_qaoa_xy_objective` is gone).

**Pull request merged**
