### PR TITLE
Pip install resolution

### PR DESCRIPTION
**Pull request by rajgane07**
Qokit code uses few Json files for calculations, these have been added back

### CODE REVIEW

**Comment by rajgane07** [comment]
This PR is to resolve bug, where some part of code will not work after pip install the repository either using pip install git+.. or pip install from pypi. The reason being during package time it configured to remove all the files under asset folder. The codes referencing some of the files will break.
Fix is move all the unwanted filed to archive folder, respective owners can check them and remove it. In the .toml only exclude the archived files.

Test this by either doing pip install git+ https://github.com/jpmorganchase/QOKit.git@test_coverage_circuit_optimization and/or pip install from pypi test site.
run following, it should not throw error. 
from qokit.parameter_utils import get_fixed_gamma_beta
get_fixed_gamma_beta(3, 1)

**Review by HaoTy — APPROVED** [review]
Yeah, this fixes #19 on my end. Thanks!

**Comment by rajgane07** [comment]
Can you wait before merge? I want to check something

**Review by alex124585 — APPROVED** [review]

**Review by rsln-s — CHANGES_REQUESTED** [review]
Install works on my machine! @rajgane07, could we make sure (using e.g. `grep`) that none of the file names under `archives/` are mentioned anywhere in the code, and then delete the `archives/` folder?

Looks great otherwise!

**Comment by rajgane07** [comment]
During pip packaging, json files/.npy files were getting excluded. This change fixes that issue. @rsln-s I created archives file after verifying there are no depenency in the code. I have removed archives folder too in this change.

All can you please verify and review one more time?

**Review by rsln-s — APPROVED** [review]
LGTM! @rajgane07, feel free to merge

**Pull request merged**
